# This pod definition hosts nginx server pod in the worker-node-01. This is manual deploying of pod if not schedulers present in the k8s cluster

apiVersion: v1

kind: Pod

metadata:
  name: nginx-server
  namespace: finance
  labels:
    app: nginx-server
    tier: frontend
    team: finance
    environment: production
    contact: boopathi-at-git.com

spec:
  containers:
    - name: nginx-server
      image: nginx
  nodeName: worker-node-01
