#This pod definition host nginx server and mount the volume from the host machine. This is not recommended for multi-node & production cluster.
# I have defined the nodeName where the pod should get hosted.

apiVersion: v1
kind: Pod
metadata:
  namespace: finance
  name: nginx-server-pvc
  labels:
    app: nginx-server
    team: finance

spec:
  containers:
    - name: nginx-server
      image: nginx
      volumeMounts:
        - name: host-path-pvc
          mountPath: /usr/share/nginx/html

  volumes:
    - name: host-path-pvc
      persistentVolumeClaim:
        claimName: pvc-small

  nodeName: node01
